version: '2.2'
services:
    web_practice:
            build: .
            command:
               python manage.py runserver 0.0.0.0:8003
            container_name: 
               web_practice
            
            ports:
               - "8003:8003"
            volumes:
               - .:/code
            restart: always
            depends_on:
               - db
   
    db:
      image:
            postgres:13
            
      environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"
            

        
   #  redis_practice:
   #      image: 
   #         redis
   #      container_name: 
   #         redis_practice
   #  celery_practice:
   #      restart: 
   #         always
   #      build:
   #         context: .
   #      container_name: celery_practice
   #      command:
   #        celery -A HealthCare worker --beat -l info --concurrency=5 -n worker1@%h
   #      volumes:
   #         - .:/code
   #      depends_on:
   #         - redis_practice
   #         - web_practice
          
