# Generated by Django 4.0.6 on 2022-08-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=200, unique=True)),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_image', models.ImageField(upload_to='doctor_img/')),
                ('doctor_dob', models.DateField()),
                ('doctor_gender', models.CharField(max_length=10)),
                ('doctor_phone', models.CharField(max_length=20)),
                ('doctor_address', models.CharField(max_length=200)),
                ('doctor_department', models.CharField(max_length=100)),
                ('doctor_qualification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=200, unique=True)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_dob', models.DateField()),
                ('patient_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='DoctorDetails',
        ),
        migrations.DeleteModel(
            name='PatientDetails',
        ),
    ]
