# Generated by Django 4.0.6 on 2022-08-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_doctordetail_patientdetail_delete_doctordetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=30, null=True)),
                ('patient_id', models.CharField(max_length=6, null=True)),
                ('patient_gender', models.CharField(max_length=10, null=True)),
                ('patient_phone', models.IntegerField(null=True)),
                ('patient_dob', models.DateField(max_length=200, null=True)),
                ('patient_password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientDetail',
        ),
    ]
