# Generated by Django 4.0.6 on 2022-08-10 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reception', '0002_doctorprofile_patientdetail_userrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30)),
                ('doctor_image', models.ImageField(upload_to='doctor_img/')),
                ('doctor_dob', models.DateField()),
                ('doctor_gender', models.CharField(max_length=10)),
                ('doctor_phone', models.IntegerField()),
                ('doctor_address', models.CharField(max_length=200)),
                ('doctor_department', models.CharField(max_length=100)),
                ('doctor_qualification', models.CharField(max_length=100)),
                ('doctor_password', models.CharField(max_length=100)),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
    ]
