# Generated by Django 4.0.6 on 2022-08-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_doctordetail_delete_doctorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=30)),
            ],
        ),
    ]
