# Generated by Django 4.0.6 on 2022-08-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetail',
            name='doctor_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.department'),
        ),
    ]
