# Generated by Django 4.0.6 on 2022-08-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_alter_doctordetail_doctor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='doctordetail',
            name='doctor_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.department', to_field='department_name'),
        ),
    ]
