# Generated by Django 4.0.6 on 2022-08-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0006_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordetail',
            name='doctor_department',
            field=models.CharField(max_length=30),
        ),
    ]
