# Generated by Django 4.0.6 on 2022-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0007_alter_doctordetail_doctor_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetail',
            name='patient_dep',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
