# Generated by Django 4.0.6 on 2022-08-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='dob',
            field=models.DateTimeField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='patient_id',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='patient_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
