# Generated by Django 4.0.6 on 2022-08-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_patientdetails_dob_patientdetails_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='dob',
            field=models.DateField(max_length=200, null=True),
        ),
    ]
