# Generated by Django 4.0.6 on 2022-08-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_patientdetails_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorDetails',
        ),
        migrations.DeleteModel(
            name='PatientDetails',
        ),
    ]
